name: rtkit
description: RealtimeKit
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  flutter_custom_tabs: ^1.2.0
  http: ^1.1.0
  mobile_scanner: ^3.4.1
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcer_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/providers/
     - assets/logo.png
  
  fonts:
  - family: HansonBold
    fonts:
      - asset: assets/Hanson-Bold-700.otf
        weight: 700
  - family: "Oskari G2"
    fonts:
      - asset: assets/OskariG2-Book.otf
  - family: OskariSemiBold
    fonts:
      - asset: assets/OskariG2-SemiBold.otf