name: Release to App Store

on:
  push:
    paths:
      - "remote/**"
    branches:
      - main
  release:
    types: [released]
  workflow_dispatch:

jobs:
  ipa:
    if: github.event_name != 'release'
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_ISSUER_ID: 863d4663-9217-4c36-9caa-e7b2201ec4f1
      APP_STORE_CONNECT_KEY_IDENTIFIER: PQPDACRFT7
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      CERTIFICATE_PRIVATE_KEY: ${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}
    concurrency: 
      group: ios-${{ github.ref }}
    environment:
      name: ios-${{ github.event_name == 'release' && 'app-store' || 'testflight' }}
      url: https://appstoreconnect.apple.com/apps/1567720948/${{ github.event_name == 'release' && 'appstore' || 'testflight' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4
        id: semantic

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: x64
      - run: pip3 install codemagic-cli-tools
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - working-directory: remote
        run: |
          keychain initialize
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --platform IOS --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles --export-options-plist=$RUNNER_TEMP/export_options.plist
          flutter pub get
          flutter build ipa --release --build-name=${{ steps.semantic.outputs.version }} --build-number=$(date +%Y%m%d%H%M) --export-options-plist=$RUNNER_TEMP/export_options.plist
          keychain use-login
      - uses: actions/upload-artifact@v2
        with:
          name: release.ipa
          path: remote/build/ios/ipa/RealtimeKit.ipa

      - run: app-store-connect publish --testflight --whats-new "New features and minor bug fixes."
      - if: github.event_name == 'release'
        run: app-store-connect publish --app-store --whats-new "New features and minor bug fixes."
