name: Remote App

on:
  push:
    paths:
      - "remote/**"
    branches:
      - main
  release:
    types: [released]
  workflow_dispatch:

jobs:
  ios:
    if: github.event_name != 'release' || endsWith(github.event.release.tag_name, '-remote')
    uses: muxable/.github/.github/workflows/flutter-ios.yml@main
    concurrency:
      group: ios-${{ github.ref }}
    with:
      working-directory: remote
      environment-name: remote-ios-${{ github.event_name == 'release' && 'app-store' || 'testflight' }}
      environment-url: https://appstoreconnect.apple.com/apps/6443628121/${{ github.event_name == 'release' && 'appstore' || 'testflight' }}
    secrets:
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      APPLE_CERTIFICATE_PRIVATE_KEY: ${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}
  android:
    if: github.event_name != 'release' || endsWith(github.event.release.tag_name, '-remote')
    uses: muxable/.github/.github/workflows/flutter-android.yml@main
    concurrency:
      group: android-${{ github.ref }}
    with:
      working-directory: remote
      environment-name: remote-android-${{ github.event_name == 'release' && 'production' || 'internal' }}
      environment-url: https://play.google.com/console/developers/8168733962061318282/app/4974769186575273826/tracks/${{ github.event_name == 'release' && 'production' || 'internal-testing' }}
    secrets:
      UPLOAD_KEYSTORE: ${{ secrets.UPLOAD_KEYSTORE }}
      UPLOAD_KEYSTORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
